apiVersion: v2
appVersion: 0.7.3
dependencies:
- name: mongodb
  repository: ""
  version: 0.7.3
- name: nats
  repository: https://nats-io.github.io/k8s/helm/charts/
  version: 0.4.2
description: A Helm chart for Kubernetes
name: control-plane
type: application
version: 0.7.3
